# Generated by Django 4.2.11 on 2025-07-26 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_hoteluser_is_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='hoteluser',
            name='business_name',
            field=models.CharField(default='OYO', max_length=100),
        ),
    ]
