# Generated by Django 4.2.11 on 2025-07-27 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_hoteluser_business_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hoteluser',
            name='business_name',
        ),
        migrations.AddField(
            model_name='hotelvendor',
            name='business_name',
            field=models.CharField(default='OYO', max_length=100),
        ),
        migrations.AddField(
            model_name='hotelvendor',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
    ]
